# Generated by Django 4.1.5 on 2023-02-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectarticle',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
