# Generated by Django 4.1.5 on 2023-02-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='ProjectTodo',
        ),
        migrations.RenameModel(
            old_name='TodoTag',
            new_name='ProjectTodoTag',
        ),
    ]
