# Generated by Django 4.1.5 on 2023-02-24 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_todo_projecttodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
