# Generated by Django 4.1.5 on 2023-03-03 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0002_alter_projectarticle_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectarticle',
            options={'ordering': ['created']},
        ),
        migrations.CreateModel(
            name='ProjectPageArticleTitle',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('project_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectpage')),
            ],
        ),
        migrations.AddField(
            model_name='projectarticle',
            name='article_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectpagearticletitle'),
        ),
    ]
