# Generated by Django 4.1.5 on 2023-03-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0003_alter_projectarticle_options_projectpagearticletitle_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectPageArticleTitle',
            new_name='ProjectPageTitle',
        ),
    ]
