# Generated by Django 4.1.5 on 2023-03-06 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_projectpagearticletitle_projectpagetitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpagetitle',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='projectarticle',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
