# Generated by Django 4.1.5 on 2023-03-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectpagetitle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
