# Generated by Django 4.1.5 on 2023-03-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectpage_page_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpagetitle',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='projectarticle',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
