# Generated by Django 4.1.5 on 2023-05-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projectpagetitle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectarticle',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
