# Generated by Django 4.1.5 on 2023-05-20 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectarticle_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectarticle',
            options={'ordering': ['-created']},
        ),
    ]
