# Generated by Django 4.1.5 on 2023-02-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_languageexample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languageexample',
            old_name='example',
            new_name='language',
        ),
    ]
