# Generated by Django 4.1.5 on 2023-02-10 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_rename_example_languageexample_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='language_created',
        ),
        migrations.AddField(
            model_name='language',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='languageexample',
            name='created',
            field=models.DateTimeField(verbose_name='created'),
        ),
    ]
