# Generated by Django 4.1.5 on 2023-05-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testaus', '0002_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
