# Generated by Django 4.1.5 on 2023-05-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testaus', '0003_alter_mymodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malli1',
            fields=[
                ('question', models.CharField(max_length=500)),
                ('empty', models.CharField(max_length=1)),
                ('answer', models.CharField(max_length=2000)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Malli2',
            fields=[
                ('question', models.CharField(max_length=500)),
                ('empty', models.CharField(max_length=1)),
                ('answer', models.CharField(max_length=2000)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
