# Generated by Django 4.1.5 on 2023-05-20 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('testaus', '0005_malli1_owner_malli2_owner_alter_malli1_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malli1',
            name='empty',
        ),
        migrations.RemoveField(
            model_name='malli2',
            name='empty',
        ),
        migrations.CreateModel(
            name='Muistipeli',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='malli1',
            name='muistipeli',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testaus.muistipeli'),
        ),
        migrations.AddField(
            model_name='malli2',
            name='muistipeli',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testaus.muistipeli'),
        ),
    ]
