# Generated by Django 4.1.5 on 2023-11-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testaus', '0010_alter_muistipeli_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswerPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
            ],
        ),
    ]
