# Generated by Django 4.1.5 on 2024-05-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testaus', '0011_questionanswerpair'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelX',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
