# Generated by Django 4.1.5 on 2023-02-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0006_languageexample_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageexample',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
